// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_TickTackToeGame_screen_init(void)
{
    ui_TickTackToeGame = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TickTackToeGame, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TickTackToeGame, &ui_img_test_venus_320x240_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_TickTackToeGame, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackHomeButton4 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_BackHomeButton4, 101);
    lv_obj_set_height(ui_BackHomeButton4, 9);
    lv_obj_set_x(ui_BackHomeButton4, -101);
    lv_obj_set_y(ui_BackHomeButton4, 112);
    lv_obj_set_align(ui_BackHomeButton4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackHomeButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackHomeButton4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackHomeButton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackHomeButton4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackHome3 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_BackHome3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackHome3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackHome3, -103);
    lv_obj_set_y(ui_BackHome3, 111);
    lv_obj_set_align(ui_BackHome3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackHome3, "Back to Home");
    lv_obj_set_style_text_color(ui_BackHome3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackHome3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BackHome3, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_TickTackToeGame);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 219);
    lv_obj_set_height(ui_Container2, 203);
    lv_obj_set_x(ui_Container2, 7);
    lv_obj_set_y(ui_Container2, 1);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xFBFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_TickTackToeGame);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 74);
    lv_obj_set_height(ui_Container3, 200);
    lv_obj_set_x(ui_Container3, -64);
    lv_obj_set_y(ui_Container3, 2);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_TickTackToeGame);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 73);
    lv_obj_set_height(ui_Container1, 201);
    lv_obj_set_x(ui_Container1, 8);
    lv_obj_set_y(ui_Container1, 2);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_TickTackToeGame);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 216);
    lv_obj_set_height(ui_Container4, 68);
    lv_obj_set_x(ui_Container4, 8);
    lv_obj_set_y(ui_Container4, 3);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0xFDFDFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos0 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos0, 67);
    lv_obj_set_height(ui_pos0, 62);
    lv_obj_set_x(ui_pos0, -65);
    lv_obj_set_y(ui_pos0, -63);
    lv_obj_set_align(ui_pos0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos1 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos1, 67);
    lv_obj_set_height(ui_pos1, 62);
    lv_obj_set_x(ui_pos1, 8);
    lv_obj_set_y(ui_pos1, -63);
    lv_obj_set_align(ui_pos1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos2 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos2, 67);
    lv_obj_set_height(ui_pos2, 62);
    lv_obj_set_x(ui_pos2, 79);
    lv_obj_set_y(ui_pos2, -65);
    lv_obj_set_align(ui_pos2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos5 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos5, 65);
    lv_obj_set_height(ui_pos5, 62);
    lv_obj_set_x(ui_pos5, 78);
    lv_obj_set_y(ui_pos5, 4);
    lv_obj_set_align(ui_pos5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos3 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos3, 67);
    lv_obj_set_height(ui_pos3, 62);
    lv_obj_set_x(ui_pos3, -64);
    lv_obj_set_y(ui_pos3, 5);
    lv_obj_set_align(ui_pos3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos4 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos4, 67);
    lv_obj_set_height(ui_pos4, 62);
    lv_obj_set_x(ui_pos4, 8);
    lv_obj_set_y(ui_pos4, 3);
    lv_obj_set_align(ui_pos4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos7 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos7, 67);
    lv_obj_set_height(ui_pos7, 62);
    lv_obj_set_x(ui_pos7, 9);
    lv_obj_set_y(ui_pos7, 71);
    lv_obj_set_align(ui_pos7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos8 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos8, 67);
    lv_obj_set_height(ui_pos8, 62);
    lv_obj_set_x(ui_pos8, 79);
    lv_obj_set_y(ui_pos8, 71);
    lv_obj_set_align(ui_pos8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pos6 = lv_btn_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_pos6, 67);
    lv_obj_set_height(ui_pos6, 62);
    lv_obj_set_x(ui_pos6, -65);
    lv_obj_set_y(ui_pos6, 72);
    lv_obj_set_align(ui_pos6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pos6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_pos6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pos6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pos6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X0 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X0, -65);
    lv_obj_set_y(ui_X0, -63);
    lv_obj_set_align(ui_X0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X0, "X");
    lv_obj_add_flag(ui_X0, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X0, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O0 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O0, -64);
    lv_obj_set_y(ui_O0, -63);
    lv_obj_set_align(ui_O0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O0, "O");
    lv_obj_add_flag(ui_O0, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O0, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X1 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X1, 9);
    lv_obj_set_y(ui_X1, -60);
    lv_obj_set_align(ui_X1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X1, "X");
    lv_obj_add_flag(ui_X1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X2 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X2, 81);
    lv_obj_set_y(ui_X2, -60);
    lv_obj_set_align(ui_X2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X2, "X");
    lv_obj_add_flag(ui_X2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X3 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X3, -66);
    lv_obj_set_y(ui_X3, 7);
    lv_obj_set_align(ui_X3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X3, "X");
    lv_obj_add_flag(ui_X3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X4 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X4, 9);
    lv_obj_set_y(ui_X4, 7);
    lv_obj_set_align(ui_X4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X4, "X");
    lv_obj_add_flag(ui_X4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X5 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X5, 81);
    lv_obj_set_y(ui_X5, 7);
    lv_obj_set_align(ui_X5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X5, "X");
    lv_obj_add_flag(ui_X5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X6 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X6, -63);
    lv_obj_set_y(ui_X6, 68);
    lv_obj_set_align(ui_X6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X6, "X");
    lv_obj_add_flag(ui_X6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X7 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X7, 10);
    lv_obj_set_y(ui_X7, 69);
    lv_obj_set_align(ui_X7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X7, "X");
    lv_obj_add_flag(ui_X7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_X8 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_X8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_X8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_X8, 80);
    lv_obj_set_y(ui_X8, 69);
    lv_obj_set_align(ui_X8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_X8, "X");
    lv_obj_add_flag(ui_X8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_X8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O1 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O1, 8);
    lv_obj_set_y(ui_O1, -62);
    lv_obj_set_align(ui_O1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O1, "O");
    lv_obj_add_flag(ui_O1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O2 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O2, 82);
    lv_obj_set_y(ui_O2, -61);
    lv_obj_set_align(ui_O2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O2, "O");
    lv_obj_add_flag(ui_O2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O3 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O3, -66);
    lv_obj_set_y(ui_O3, 6);
    lv_obj_set_align(ui_O3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O3, "O");
    lv_obj_add_flag(ui_O3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O4 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O4, 8);
    lv_obj_set_y(ui_O4, 7);
    lv_obj_set_align(ui_O4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O4, "O");
    lv_obj_add_flag(ui_O4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O5 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O5, 80);
    lv_obj_set_y(ui_O5, 6);
    lv_obj_set_align(ui_O5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O5, "O");
    lv_obj_add_flag(ui_O5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O5, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O6 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O6, -64);
    lv_obj_set_y(ui_O6, 67);
    lv_obj_set_align(ui_O6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O6, "O");
    lv_obj_add_flag(ui_O6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O6, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O7 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O7, 12);
    lv_obj_set_y(ui_O7, 67);
    lv_obj_set_align(ui_O7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O7, "O");
    lv_obj_add_flag(ui_O7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O8 = lv_label_create(ui_TickTackToeGame);
    lv_obj_set_width(ui_O8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O8, 80);
    lv_obj_set_y(ui_O8, 68);
    lv_obj_set_align(ui_O8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O8, "O");
    lv_obj_add_flag(ui_O8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_O8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackHomeButton4, ui_event_BackHomeButton4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos0, ui_event_pos0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos1, ui_event_pos1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos2, ui_event_pos2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos5, ui_event_pos5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos3, ui_event_pos3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos4, ui_event_pos4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos7, ui_event_pos7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos8, ui_event_pos8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pos6, ui_event_pos6, LV_EVENT_ALL, NULL);

}
