// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_InfoScreen_screen_init(void)
{
    ui_InfoScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InfoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_InfoScreen, &ui_img_test_venus_320x240_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_InfoScreen, 130, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoContainer = lv_obj_create(ui_InfoScreen);
    lv_obj_remove_style_all(ui_InfoContainer);
    lv_obj_set_width(ui_InfoContainer, 253);
    lv_obj_set_height(ui_InfoContainer, 152);
    lv_obj_set_x(ui_InfoContainer, 2);
    lv_obj_set_y(ui_InfoContainer, 8);
    lv_obj_set_align(ui_InfoContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_InfoContainer, lv_color_hex(0xEBE01E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InfoContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_InfoContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_InfoContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_InfoContainer, lv_color_hex(0xEDEDED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_InfoContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_InfoContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_InfoContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_InfoContainer, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InfoContainer, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_InfoContainer, LV_BORDER_SIDE_TOP, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_CurrentStateLabel = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_CurrentStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentStateLabel, -35);
    lv_obj_set_y(ui_CurrentStateLabel, -70);
    lv_obj_set_align(ui_CurrentStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentStateLabel, "Current state:");
    lv_obj_set_style_text_color(ui_CurrentStateLabel, lv_color_hex(0xF9F6F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentStateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentStateLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_CurrentStateLabel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CurrentStateLabel, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CurrentStateLabel, 220, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temperature = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, -21);
    lv_obj_set_y(ui_Temperature, -38);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "Temperature:    XX°C");
    lv_obj_set_style_text_color(ui_Temperature, lv_color_hex(0xEBEAE0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, -22);
    lv_obj_set_y(ui_Humidity, -11);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humidity, "Humidity:          XX%");
    lv_obj_set_style_text_color(ui_Humidity, lv_color_hex(0xEBEBEA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Humidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Accelerometer = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_Accelerometer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accelerometer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accelerometer, -16);
    lv_obj_set_y(ui_Accelerometer, 17);
    lv_obj_set_align(ui_Accelerometer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accelerometer, "Acc (X):              x.xxxx");
    lv_obj_set_style_text_color(ui_Accelerometer, lv_color_hex(0xEBEBE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Accelerometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Accelerometer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date2 = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_Date2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date2, -104);
    lv_obj_set_y(ui_Date2, -103);
    lv_obj_set_align(ui_Date2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date2, "DD:MM:YYYY");
    lv_obj_set_style_text_font(ui_Date2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hour2 = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_Hour2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hour2, 111);
    lv_obj_set_y(ui_Hour2, -101);
    lv_obj_set_align(ui_Hour2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour2, "HH:MM:SS");
    lv_obj_set_style_text_font(ui_Hour2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackHomeButton3 = lv_btn_create(ui_InfoScreen);
    lv_obj_set_width(ui_BackHomeButton3, 117);
    lv_obj_set_height(ui_BackHomeButton3, 20);
    lv_obj_set_x(ui_BackHomeButton3, -98);
    lv_obj_set_y(ui_BackHomeButton3, 106);
    lv_obj_set_align(ui_BackHomeButton3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackHomeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackHomeButton3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackHomeButton3, lv_color_hex(0xF1EE72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackHomeButton3, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackHome4 = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_BackHome4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackHome4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BackHome4, -98);
    lv_obj_set_y(ui_BackHome4, 106);
    lv_obj_set_align(ui_BackHome4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackHome4, "Back to Home");
    lv_obj_set_style_text_color(ui_BackHome4, lv_color_hex(0x28375F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BackHome4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Accelerometer1 = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_Accelerometer1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accelerometer1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accelerometer1, -16);
    lv_obj_set_y(ui_Accelerometer1, 43);
    lv_obj_set_align(ui_Accelerometer1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accelerometer1, "Acc(Y):               y.yyyy");
    lv_obj_set_style_text_color(ui_Accelerometer1, lv_color_hex(0xEBEBE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Accelerometer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Accelerometer1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Accelerometer2 = lv_label_create(ui_InfoScreen);
    lv_obj_set_width(ui_Accelerometer2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Accelerometer2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Accelerometer2, -16);
    lv_obj_set_y(ui_Accelerometer2, 67);
    lv_obj_set_align(ui_Accelerometer2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Accelerometer2, "Acc (Z):              z.zzzz");
    lv_obj_set_style_text_color(ui_Accelerometer2, lv_color_hex(0xEBEBE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Accelerometer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Accelerometer2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BackHomeButton3, ui_event_BackHomeButton3, LV_EVENT_ALL, NULL);

}
