// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_JoystickScreen_screen_init(void)
{
    ui_JoystickScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_JoystickScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_JoystickScreen, &ui_img_test_venus_320x240_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_JoystickScreen, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NLO = lv_img_create(ui_JoystickScreen);
    lv_img_set_src(ui_NLO, &ui_img_1806197300);
    lv_obj_set_width(ui_NLO, lv_pct(19));
    lv_obj_set_height(ui_NLO, lv_pct(16));
    lv_obj_set_x(ui_NLO, 17);
    lv_obj_set_y(ui_NLO, -12);
    lv_obj_set_align(ui_NLO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NLO, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NLO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_NLO, &ui_img_1806197300, LV_PART_MAIN | LV_STATE_DEFAULT);

}
