// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_WelcomeText;
void ui_event_InfoButton(lv_event_t * e);
lv_obj_t * ui_InfoButton;
void ui_event_StartGameButton(lv_event_t * e);
lv_obj_t * ui_StartGameButton;
lv_obj_t * ui_InfoText;
lv_obj_t * ui_StartGameText;
lv_obj_t * ui_BitTraveller;
lv_obj_t * ui_Date;
lv_obj_t * ui_Hour;


// SCREEN: ui_StartGameScreen
void ui_StartGameScreen_screen_init(void);
lv_obj_t * ui_StartGameScreen;
lv_obj_t * ui_Date3;
lv_obj_t * ui_Hour3;
lv_obj_t * ui_TicTackToeLabel;
lv_obj_t * ui_selectSignLabel;
void ui_event_XButton(lv_event_t * e);
lv_obj_t * ui_XButton;
void ui_event_OButton(lv_event_t * e);
lv_obj_t * ui_OButton;
lv_obj_t * ui_XLabel;
lv_obj_t * ui_OLabel;
void ui_event_BackHomeButton2(lv_event_t * e);
lv_obj_t * ui_BackHomeButton2;
lv_obj_t * ui_BackHome2;


// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
lv_obj_t * ui_InfoScreen;
lv_obj_t * ui_InfoContainer;
lv_obj_t * ui_CurrentStateLabel;
lv_obj_t * ui_Temperature;
lv_obj_t * ui_Humidity;
lv_obj_t * ui_Accelerometer;
lv_obj_t * ui_Date2;
lv_obj_t * ui_Hour2;
void ui_event_BackHomeButton3(lv_event_t * e);
lv_obj_t * ui_BackHomeButton3;
lv_obj_t * ui_BackHome4;
lv_obj_t * ui_Accelerometer1;
lv_obj_t * ui_Accelerometer2;


// SCREEN: ui_TickTackToeGame
void ui_TickTackToeGame_screen_init(void);
lv_obj_t * ui_TickTackToeGame;
void ui_event_BackHomeButton4(lv_event_t * e);
lv_obj_t * ui_BackHomeButton4;
lv_obj_t * ui_BackHome3;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container4;
void ui_event_pos0(lv_event_t * e);
lv_obj_t * ui_pos0;
void ui_event_pos1(lv_event_t * e);
lv_obj_t * ui_pos1;
void ui_event_pos2(lv_event_t * e);
lv_obj_t * ui_pos2;
void ui_event_pos5(lv_event_t * e);
lv_obj_t * ui_pos5;
void ui_event_pos3(lv_event_t * e);
lv_obj_t * ui_pos3;
void ui_event_pos4(lv_event_t * e);
lv_obj_t * ui_pos4;
void ui_event_pos7(lv_event_t * e);
lv_obj_t * ui_pos7;
void ui_event_pos8(lv_event_t * e);
lv_obj_t * ui_pos8;
void ui_event_pos6(lv_event_t * e);
lv_obj_t * ui_pos6;
lv_obj_t * ui_X0;
lv_obj_t * ui_O0;
lv_obj_t * ui_X1;
lv_obj_t * ui_X2;
lv_obj_t * ui_X3;
lv_obj_t * ui_X4;
lv_obj_t * ui_X5;
lv_obj_t * ui_X6;
lv_obj_t * ui_X7;
lv_obj_t * ui_X8;
lv_obj_t * ui_O1;
lv_obj_t * ui_O2;
lv_obj_t * ui_O3;
lv_obj_t * ui_O4;
lv_obj_t * ui_O5;
lv_obj_t * ui_O6;
lv_obj_t * ui_O7;
lv_obj_t * ui_O8;


// SCREEN: ui_EndGameScreen
void ui_EndGameScreen_screen_init(void);
lv_obj_t * ui_EndGameScreen;
lv_obj_t * ui_Date1;
lv_obj_t * ui_Hour1;
lv_obj_t * ui_GameOverLabel;
lv_obj_t * ui_WinLabel;
lv_obj_t * ui_LoseLabel;
void ui_event_BackHomeButton(lv_event_t * e);
lv_obj_t * ui_BackHomeButton;
lv_obj_t * ui_BackHome;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_venus_320x[1] = {&ui_img_test_venus_320x240_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_InfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InfoScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_InfoScreen_screen_init);
    }
}
void ui_event_StartGameButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StartGameScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_StartGameScreen_screen_init);
    }
}
void ui_event_XButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        startWithX(e);
    }
}
void ui_event_OButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        startWithO(e);
    }
}
void ui_event_BackHomeButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_BackHomeButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_BackHomeButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_pos0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position0_clicked(e);
    }
}
void ui_event_pos1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position1_clicked(e);
    }
}
void ui_event_pos2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position2_clicked(e);
    }
}
void ui_event_pos5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position5_clicked(e);
    }
}
void ui_event_pos3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position3_clicked(e);
    }
}
void ui_event_pos4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position4_clicked(e);
    }
}
void ui_event_pos7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position7_clicked(e);
    }
}
void ui_event_pos8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position8_clicked(e);
    }
}
void ui_event_pos6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        position6_clicked(e);
    }
}
void ui_event_BackHomeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_MainScreen_screen_init();
    ui_StartGameScreen_screen_init();
    ui_InfoScreen_screen_init();
    ui_TickTackToeGame_screen_init();
    ui_EndGameScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_MainScreen);
}
