// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_WelcomeText;
void ui_event_InfoButton(lv_event_t * e);
extern lv_obj_t * ui_InfoButton;
void ui_event_StartGameButton(lv_event_t * e);
extern lv_obj_t * ui_StartGameButton;
extern lv_obj_t * ui_InfoText;
extern lv_obj_t * ui_StartGameText;
extern lv_obj_t * ui_BitTraveller;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Hour;
// SCREEN: ui_StartGameScreen
void ui_StartGameScreen_screen_init(void);
extern lv_obj_t * ui_StartGameScreen;
extern lv_obj_t * ui_Date3;
extern lv_obj_t * ui_Hour3;
extern lv_obj_t * ui_TicTackToeLabel;
extern lv_obj_t * ui_selectSignLabel;
void ui_event_XButton(lv_event_t * e);
extern lv_obj_t * ui_XButton;
void ui_event_OButton(lv_event_t * e);
extern lv_obj_t * ui_OButton;
extern lv_obj_t * ui_XLabel;
extern lv_obj_t * ui_OLabel;
void ui_event_BackHomeButton2(lv_event_t * e);
extern lv_obj_t * ui_BackHomeButton2;
extern lv_obj_t * ui_BackHome2;
// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
extern lv_obj_t * ui_InfoScreen;
extern lv_obj_t * ui_InfoContainer;
extern lv_obj_t * ui_CurrentStateLabel;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_Accelerometer;
extern lv_obj_t * ui_Date2;
extern lv_obj_t * ui_Hour2;
void ui_event_BackHomeButton3(lv_event_t * e);
extern lv_obj_t * ui_BackHomeButton3;
extern lv_obj_t * ui_BackHome4;
extern lv_obj_t * ui_Accelerometer1;
extern lv_obj_t * ui_Accelerometer2;
// SCREEN: ui_TickTackToeGame
void ui_TickTackToeGame_screen_init(void);
extern lv_obj_t * ui_TickTackToeGame;
void ui_event_BackHomeButton4(lv_event_t * e);
extern lv_obj_t * ui_BackHomeButton4;
extern lv_obj_t * ui_BackHome3;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container4;
void ui_event_pos0(lv_event_t * e);
extern lv_obj_t * ui_pos0;
void ui_event_pos1(lv_event_t * e);
extern lv_obj_t * ui_pos1;
void ui_event_pos2(lv_event_t * e);
extern lv_obj_t * ui_pos2;
void ui_event_pos5(lv_event_t * e);
extern lv_obj_t * ui_pos5;
void ui_event_pos3(lv_event_t * e);
extern lv_obj_t * ui_pos3;
void ui_event_pos4(lv_event_t * e);
extern lv_obj_t * ui_pos4;
void ui_event_pos7(lv_event_t * e);
extern lv_obj_t * ui_pos7;
void ui_event_pos8(lv_event_t * e);
extern lv_obj_t * ui_pos8;
void ui_event_pos6(lv_event_t * e);
extern lv_obj_t * ui_pos6;
extern lv_obj_t * ui_X0;
extern lv_obj_t * ui_O0;
extern lv_obj_t * ui_X1;
extern lv_obj_t * ui_X2;
extern lv_obj_t * ui_X3;
extern lv_obj_t * ui_X4;
extern lv_obj_t * ui_X5;
extern lv_obj_t * ui_X6;
extern lv_obj_t * ui_X7;
extern lv_obj_t * ui_X8;
extern lv_obj_t * ui_O1;
extern lv_obj_t * ui_O2;
extern lv_obj_t * ui_O3;
extern lv_obj_t * ui_O4;
extern lv_obj_t * ui_O5;
extern lv_obj_t * ui_O6;
extern lv_obj_t * ui_O7;
extern lv_obj_t * ui_O8;
// SCREEN: ui_EndGameScreen
void ui_EndGameScreen_screen_init(void);
extern lv_obj_t * ui_EndGameScreen;
extern lv_obj_t * ui_Date1;
extern lv_obj_t * ui_Hour1;
extern lv_obj_t * ui_GameOverLabel;
extern lv_obj_t * ui_WinLabel;
extern lv_obj_t * ui_LoseLabel;
void ui_event_BackHomeButton(lv_event_t * e);
extern lv_obj_t * ui_BackHomeButton;
extern lv_obj_t * ui_BackHome;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_test_venus_320x240_png);    // assets/test/venus_320x240.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
