// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void startWithX(lv_event_t * e)
{
	// Your code here
}

void startWithO(lv_event_t * e)
{
	// Your code here
}

void position0_clicked(lv_event_t * e)
{
	// Your code here
}

void position1_clicked(lv_event_t * e)
{
	// Your code here
}

void position2_clicked(lv_event_t * e)
{
	// Your code here
}

void position5_clicked(lv_event_t * e)
{
	// Your code here
}

void position3_clicked(lv_event_t * e)
{
	// Your code here
}

void position4_clicked(lv_event_t * e)
{
	// Your code here
}

void position7_clicked(lv_event_t * e)
{
	// Your code here
}

void position8_clicked(lv_event_t * e)
{
	// Your code here
}

void position6_clicked(lv_event_t * e)
{
	// Your code here
}
