// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "mqtt_driver.h"

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startWithX(lv_event_t * e);
void startWithO(lv_event_t * e);
void position0_clicked(lv_event_t * e);
void position1_clicked(lv_event_t * e);
void position2_clicked(lv_event_t * e);
void position5_clicked(lv_event_t * e);
void position3_clicked(lv_event_t * e);
void position4_clicked(lv_event_t * e);
void position7_clicked(lv_event_t * e);
void position8_clicked(lv_event_t * e);
void position6_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
