// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include <stdio.h>
#include "TicTacToe.h"
#include "ui_events.h"

char myChar;

void clearGui(void) {
	lv_obj_add_flag(ui_X0, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O0, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O1, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O2, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O3, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X4, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O4, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X5, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O5, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X6, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O6, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X7, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O7, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_X8, LV_OBJ_FLAG_HIDDEN);
	lv_obj_add_flag(ui_O8, LV_OBJ_FLAG_HIDDEN);
}

void gui_move(int id, lv_obj_t *X_obj, lv_obj_t *O_obj) {
	player p = getCurrentPlayer();
	
	if(p == DEVICE) {
		game_status m = makeMove(myChar, id);
		if(m == INVALID_MOVE) {
			return;
		}

		if (myChar == 'x')
			lv_obj_clear_flag(X_obj, LV_OBJ_FLAG_HIDDEN);
		else 
			lv_obj_clear_flag(O_obj, LV_OBJ_FLAG_HIDDEN);

		if (m == GAME_WON) {
			lv_obj_clear_flag(ui_WinLabel, LV_OBJ_FLAG_HIDDEN);
			lv_obj_add_flag(ui_LoseLabel, LV_OBJ_FLAG_HIDDEN);
			_ui_screen_change(&ui_EndGameScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_EndGameScreen_screen_init);
			clearGui();
		}else if (m == GAME_ENDED) {
			lv_label_set_text(ui_LoseLabel, "Game ended in a draw!");
			lv_obj_clear_flag(ui_LoseLabel, LV_OBJ_FLAG_HIDDEN);
			lv_obj_add_flag(ui_WinLabel, LV_OBJ_FLAG_HIDDEN);
			_ui_screen_change(&ui_EndGameScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_EndGameScreen_screen_init);
			clearGui();
		}

		// mqtt message
		send_game_message("server", get_game_array());
	}
}

void startWithX(lv_event_t * e)
{
	startGame('x');
	myChar = 'x';

	_ui_screen_change(&ui_TickTackToeGame, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TickTackToeGame_screen_init);
}

void startWithO(lv_event_t * e)
{
	startGame('o');
	myChar = 'o';

	_ui_screen_change(&ui_TickTackToeGame, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_TickTackToeGame_screen_init);
	
	// NEEDED FOR GAME TO START PROPPERLY!!!
	send_game_message("server", get_game_array());
}

void position0_clicked(lv_event_t * e)
{
	gui_move(0, ui_X0, ui_O0);
}

void position1_clicked(lv_event_t * e)
{
	gui_move(1, ui_X1, ui_O1);
}

void position2_clicked(lv_event_t * e)
{
	gui_move(2, ui_X2, ui_O2);
}

void position5_clicked(lv_event_t * e)
{
	gui_move(5, ui_X5, ui_O5);
}

void position3_clicked(lv_event_t * e)
{
	gui_move(3, ui_X3, ui_O3);
}

void position4_clicked(lv_event_t * e)
{
	gui_move(4, ui_X4, ui_O4);
}

void position7_clicked(lv_event_t * e)
{
	gui_move(7, ui_X7, ui_O7);
}

void position8_clicked(lv_event_t * e)
{
	gui_move(8, ui_X8, ui_O8);
}

void position6_clicked(lv_event_t * e)
{
	gui_move(6, ui_X6, ui_O6);
}
